// Error codes for standardized error handling
export enum ErrorCode {
  // General errors
  UNKNOWN = "UNKNOWN_ERROR",
  NOT_IMPLEMENTED = "NOT_IMPLEMENTED",
  NETWORK_ERROR = "NETWORK_ERROR",
  SERVER_ERROR = "SERVER_ERROR",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  NOT_FOUND = "NOT_FOUND",
  TOO_MANY_ATTEMPTS = "TOO_MANY_ATTEMPTS",
  
  // Phone validation errors
  PHONE_INVALID = "PHONE_INVALID",
  PHONE_REQUIRED = "PHONE_REQUIRED",
  PHONE_NOT_REGISTERED = "PHONE_NOT_REGISTERED",
  PHONE_ALREADY_REGISTERED = "PHONE_ALREADY_REGISTERED",

  // Email validation errors
  EMAIL_INVALID = "EMAIL_INVALID",
  EMAIL_ALREADY_REGISTERED = "EMAIL_ALREADY_REGISTERED",
  
  // OTP verification errors
  OTP_MISSING_MEDIUM = "OTP_MISSING_MEDIUM",
  OTP_INVALID = "OTP_INVALID",
  OTP_EXPIRED = "OTP_EXPIRED",
  OTP_REQUIRED = "OTP_REQUIRED",
  OTP_SEND_FAILED = "OTP_SEND_FAILED",
  OTP_VERIFY_FAILED = "OTP_VERIFY_FAILED",
  OTP_RESEND_FAILED = "OTP_RESEND_FAILED",
  TOO_MANY_OTP_ATTEMPTS = "TOO_MANY_OTP_ATTEMPTS",
  OTP_MAX_ATTEMPTS_EXCEEDED = "OTP_MAX_ATTEMPTS_EXCEEDED",
  OTP_LOCKED = "OTP_LOCKED", // Added for temporary lockout
  

  // Auth flow
  AUTH_FLOW_UNKNOWN_SIDE_EFFECT_ERROR = "UNKNOWN_SIDE_EFFECT_ERROR",

  // PIN errors
  PIN_INVALID = "PIN_INVALID",
  PIN_REQUIRED = "PIN_REQUIRED",
  PIN_MISMATCH = "PIN_MISMATCH",
  PIN_SET_FAILED = "PIN_SET_FAILED",
  TOO_MANY_PIN_ATTEMPTS = "TOO_MANY_PIN_ATTEMPTS",
  TOKEN_SAVE_FAILED = "TOKEN_SAVE_FAILED",
  
  // Profile errors
  PROFILE_CREATE_FAILED = "PROFILE_CREATE_FAILED",
  PROFILE_UPDATE_FAILED = "PROFILE_UPDATE_FAILED",
  
  // Token errors
  TOKEN_ACQUISITION_FAILED = "TOKEN_ACQUISITION_FAILED",
  TOKEN_VALIDATION_FAILED = "TOKEN_VALIDATION_FAILED",
  
  // Transaction errors
  TRANSACTION_FAILED = "TRANSACTION_FAILED",
  INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS",
  INVALID_AMOUNT = "INVALID_AMOUNT",
  INVALID_RECIPIENT = "INVALID_RECIPIENT",
  INVALID_METHOD = "INVALID_METHOD",
  TRANSACTION_FETCH_ERROR = "TRANSACTION_FETCH_ERROR",
  TRANSACTION_NOT_FOUND = "TRANSACTION_NOT_FOUND",
  TRANSACTION_LIST_FAILED = "TRANSACTION_LIST_FAILED",
  CASH_OUT_FAILED = "CASH_OUT_FAILED",
  
  // User errors
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_FETCH_FAILED = "USER_FETCH_FAILED",
  USER_UPDATE_FAILED = "USER_UPDATE_FAILED",
  USER_ALREADY_REGISTERED = "USER_ALREADY_REGISTERED",
  USER_UPDATE_MISSING_INFORMATION = "USER_UPDATE_MISSING_INFORMATION",
  USER_CANNOT_UPDATE_EMAIL_PHONE = "USER_CANNOT_UPDATE_EMAIL_PHONE",

  // BALANCES
  BALANCES_REFRESH_FAILED = "FAILED_TO_REFRESH_BALANCES",
  BALANCES_UNKNOWN_ISSUE = "BALANCES_UNKNOWN_ISSUE",

  // Contact management errors (for contact-based transaction resolution)
  CONTACT_NOT_FOUND = "CONTACT_NOT_FOUND",
  CONTACT_SYNC_FAILED = "CONTACT_SYNC_FAILED",
  CONTACT_PHONE_HASH_MISMATCH = "CONTACT_PHONE_HASH_MISMATCH",
  CONTACT_ALREADY_EXISTS = "CONTACT_ALREADY_EXISTS",
  CONTACT_INVALID_PHONE = "CONTACT_INVALID_PHONE",

  // Blockchain/Network specific errors
  BLOCKCHAIN_NETWORK_ERROR = "BLOCKCHAIN_NETWORK_ERROR",
  BLOCKCHAIN_TRANSACTION_FAILED = "BLOCKCHAIN_TRANSACTION_FAILED",
  BLOCKCHAIN_INSUFFICIENT_GAS = "BLOCKCHAIN_INSUFFICIENT_GAS",
  BLOCKCHAIN_TRANSACTION_REVERTED = "BLOCKCHAIN_TRANSACTION_REVERTED",
  BLOCKCHAIN_CONFIRMATION_TIMEOUT = "BLOCKCHAIN_CONFIRMATION_TIMEOUT",
  BLOCKCHAIN_INVALID_ADDRESS = "BLOCKCHAIN_INVALID_ADDRESS",
  BLOCKCHAIN_NODE_UNAVAILABLE = "BLOCKCHAIN_NODE_UNAVAILABLE",

  // Asset/Token errors
  ASSET_NOT_SUPPORTED = "ASSET_NOT_SUPPORTED",
  ASSET_INSUFFICIENT_BALANCE = "ASSET_INSUFFICIENT_BALANCE",
  ASSET_TRANSFER_DISABLED = "ASSET_TRANSFER_DISABLED",
  ASSET_MINIMUM_AMOUNT_NOT_MET = "ASSET_MINIMUM_AMOUNT_NOT_MET",
  ASSET_MAXIMUM_AMOUNT_EXCEEDED = "ASSET_MAXIMUM_AMOUNT_EXCEEDED",

  // Compliance/Regulatory errors
  TRANSACTION_LIMIT_EXCEEDED = "TRANSACTION_LIMIT_EXCEEDED",
  DAILY_LIMIT_EXCEEDED = "DAILY_LIMIT_EXCEEDED",
  MONTHLY_LIMIT_EXCEEDED = "MONTHLY_LIMIT_EXCEEDED",
  KYC_VERIFICATION_REQUIRED = "KYC_VERIFICATION_REQUIRED",
  RESTRICTED_JURISDICTION = "RESTRICTED_JURISDICTION",
  ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED",

  // Security/Fraud detection errors
  SUSPICIOUS_ACTIVITY_DETECTED = "SUSPICIOUS_ACTIVITY_DETECTED",
  TRANSACTION_BLOCKED_BY_SECURITY = "TRANSACTION_BLOCKED_BY_SECURITY",
  DEVICE_NOT_TRUSTED = "DEVICE_NOT_TRUSTED",
  GEOLOCATION_RESTRICTED = "GEOLOCATION_RESTRICTED",
  VELOCITY_CHECK_FAILED = "VELOCITY_CHECK_FAILED",

  // Sync/Offline errors (for local-first architecture)
  SYNC_CONFLICT = "SYNC_CONFLICT",
  LOCAL_DATA_CORRUPTED = "LOCAL_DATA_CORRUPTED",
  SYNC_IN_PROGRESS = "SYNC_IN_PROGRESS",
  OFFLINE_MODE_LIMITATION = "OFFLINE_MODE_LIMITATION",
  DATA_MIGRATION_REQUIRED = "DATA_MIGRATION_REQUIRED",

  // QR Code/Payment request errors
  QR_CODE_INVALID = "QR_CODE_INVALID",
  QR_CODE_EXPIRED = "QR_CODE_EXPIRED",
  PAYMENT_REQUEST_EXPIRED = "PAYMENT_REQUEST_EXPIRED",
  PAYMENT_REQUEST_ALREADY_FULFILLED = "PAYMENT_REQUEST_ALREADY_FULFILLED",
  QR_SCAN_FAILED = "QR_SCAN_FAILED",

  // Web3Auth/Wallet errors
  WALLET_NOT_CONNECTED = "WALLET_NOT_CONNECTED",
  WALLET_CONNECTION_FAILED = "WALLET_CONNECTION_FAILED",
  PRIVATE_KEY_ACCESS_DENIED = "PRIVATE_KEY_ACCESS_DENIED",
  SIGNATURE_REJECTED = "SIGNATURE_REJECTED",
  WALLET_LOCKED = "WALLET_LOCKED",
}
