// Error codes for standardized error handling
export enum ErrorCode {
  // General errors
  UNKNOWN = "UNKNOWN_ERROR",
  NETWORK_ERROR = "NETWORK_ERROR",
  SERVER_ERROR = "SERVER_ERROR",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  
  // Phone validation errors
  PHONE_INVALID = "PHONE_INVALID",
  PHONE_REQUIRED = "PHONE_REQUIRED",
  PHONE_NOT_REGISTERED = "PHONE_NOT_REGISTERED",
  PHONE_ALREADY_REGISTERED = "PHONE_ALREADY_REGISTERED",
  TOO_MANY_ATTEMPTS = "TOO_MANY_ATTEMPTS",
  
  // OTP verification errors
  OTP_INVALID = "OTP_INVALID",
  OTP_EXPIRED = "OTP_EXPIRED",
  OTP_REQUIRED = "OTP_REQUIRED",
  TOO_MANY_OTP_ATTEMPTS = "TOO_MANY_OTP_ATTEMPTS",
  
  // PIN errors
  PIN_INVALID = "PIN_INVALID",
  PIN_REQUIRED = "PIN_REQUIRED",
  PIN_MISMATCH = "PIN_MISMATCH",
  TOO_MANY_PIN_ATTEMPTS = "TOO_MANY_PIN_ATTEMPTS",
  TOKEN_SAVE_FAILED = "TOKEN_SAVE_FAILED",
  
  // Transaction errors
  TRANSACTION_FAILED = "TRANSACTION_FAILED",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  NOT_FOUND = "NOT_FOUND",
  INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS",
}
